//
//  AddListItemModels.swift
//  ShoppingList
//
//  Created by Mihai on 3/13/17.
//  Copyright (c) 2017 Mihai. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//
//  Type "usecase" for some magic!

import UIKit



struct AddListItemScene {
    struct ListItemVM {
        var name: String
        var category: String
        var quantity: Int
    }
    
    struct GetItemOnLoad {
        
        struct Request {
            
        }
        
        struct Response {
            var item: ListItem?
        }
        
        struct ViewModel {
            var item: ListItemVM
            var navTitle: String
        }
    }
    
    struct SaveItem {
        
        struct Request {
            var item: ListItemVM
        }
        
        struct Response {
            enum Result {
                case saved
                case saveError
                case invalidName
                case invalidQuantity
                case none
            }
            var result: Result
        }
        
        struct ViewModel {
            var success: Bool
            var errorMessage: String
        }
    }
    
    struct SuggestNames {
        
        struct Request {
            var filter: String
        }
        
        struct Response {
            var names: [String]
        }
        
        struct ViewModel {
            var names: [String]
        }
    }
    
    struct GetCategory {
        
        struct Request {
            var name: String
        }
        
        struct Response {
            var category: String
        }
        
        struct ViewModel {
            var category: String
        }
    }
}
