//
//  AddListItemRouter.swift
//  ShoppingList
//
//  Created by Mihai on 3/13/17.
//  Copyright (c) 2017 Mihai. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

protocol AddListItemRouterInput {
    
}

protocol AddListItemRouterDataSource:class {
    
}

protocol AddListItemRouterDataDestination:class {
    var item: ListItem? { get set }
}

class AddListItemRouter: AddListItemRouterInput {
    
    weak var viewController:AddListItemViewController!
    weak private var dataSource:AddListItemRouterDataSource!
    weak var dataDestination:AddListItemRouterDataDestination!
    
    init(viewController:AddListItemViewController, dataSource:AddListItemRouterDataSource, dataDestination:AddListItemRouterDataDestination) {
        self.viewController = viewController
        self.dataSource = dataSource
        self.dataDestination = dataDestination
    }
    
    // MARK: Navigation
    func navigateToList() {
        _ = viewController.navigationController?.popViewController(animated: true)
    }
    // MARK: Communication
    
    func passDataToNextScene(for segue: UIStoryboardSegue) {
        // NOTE: Teach the router which scenes it can communicate with
        
    }
}
