source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'ShoppingList' do
    pod 'Font-Awesome-Swift', '~> 1.6.1'
    pod 'Firebase/Database'
    pod 'SwiftyJSON'
    pod 'Toaster', '~> 2.0'
end
