//
//  ItemsInCategoryConfigurator.swift
//  ShoppingList
//
//  Created by Mihai on 3/25/17.
//  Copyright (c) 2017 Mihai. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

// MARK: Connect View, Interactor, and Presenter

extension ItemsInCategoryInteractor: ItemsInCategoryViewControllerOutput, ItemsInCategoryRouterDataSource, ItemsInCategoryRouterDataDestination {
}

extension ItemsInCategoryPresenter: ItemsInCategoryInteractorOutput {
}

class ItemsInCategoryConfigurator {
    // MARK: Object lifecycle
    
    static let sharedInstance = ItemsInCategoryConfigurator()
    
    private init() {}
    
    // MARK: Configuration
    
    func configure(viewController: ItemsInCategoryViewController) {
        
        let presenter = ItemsInCategoryPresenter()
        presenter.output = viewController
        
        let interactor = ItemsInCategoryInteractor()
        interactor.output = presenter
        interactor.statisticsStore = FirebaseStatisticsStore()
        
        let router = ItemsInCategoryRouter(viewController:viewController, dataSource:interactor, dataDestination:interactor)
        
        viewController.output = interactor
        viewController.router = router
    }
}
