//
//  ItemsInCategoryPresenter.swift
//  ShoppingList
//
//  Created by Mihai on 3/25/17.
//  Copyright (c) 2017 Mihai. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

protocol ItemsInCategoryPresenterInput {
    func presentItems(response: ItemsInCategoryScene.GetItems.Response)
}

protocol ItemsInCategoryPresenterOutput: class {
    func displayItems(viewModel: ItemsInCategoryScene.GetItems.ViewModel)
}

class ItemsInCategoryPresenter: ItemsInCategoryPresenterInput {
    
    weak var output: ItemsInCategoryPresenterOutput!
    
    // MARK: Presentation logic
    func presentItems(response: ItemsInCategoryScene.GetItems.Response) {
        output.displayItems(viewModel: ItemsInCategoryScene.GetItems.ViewModel(event: response.event))
    }
}
