//
//  CategoriesListConfigurator.swift
//  ShoppingList
//
//  Created by Mihai on 3/18/17.
//  Copyright (c) 2017 Mihai. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

// MARK: Connect View, Interactor, and Presenter

extension CategoriesListInteractor: CategoriesListViewControllerOutput, CategoriesListRouterDataSource, CategoriesListRouterDataDestination {
}

extension CategoriesListPresenter: CategoriesListInteractorOutput {
}

class CategoriesListConfigurator {
    // MARK: Object lifecycle
    
    static let sharedInstance = CategoriesListConfigurator()
    
    private init() {}
    
    // MARK: Configuration
    
    func configure(viewController: CategoriesListViewController) {
        
        let presenter = CategoriesListPresenter()
        presenter.output = viewController
        
        let interactor = CategoriesListInteractor()
        interactor.output = presenter
        interactor.categoriesStore = FirebaseCategoryStore()
        interactor.itemDataSource = ItemDataSource<Category>()
        
        let router = CategoriesListRouter(viewController:viewController, dataSource:interactor, dataDestination:interactor)
        
        viewController.output = interactor
        viewController.router = router
    }
}
