//
//  CategoriesListPresenter.swift
//  ShoppingList
//
//  Created by Mihai on 3/18/17.
//  Copyright (c) 2017 Mihai. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

protocol CategoriesListPresenterInput: CategoriesListInteractorOutput {
}

protocol CategoriesListPresenterOutput: class {
    func displayDataEvent(viewModel: CategoriesListScene.GetCategories.ViewModel)
}

class CategoriesListPresenter: CategoriesListPresenterInput {
    
    weak var output: CategoriesListPresenterOutput!
    
    // MARK: Presentation logic
    func presentDataEvent(response: CategoriesListScene.GetCategories.Response) {
        output.displayDataEvent(viewModel: CategoriesListScene.GetCategories.ViewModel(dataEvent: response.dataEvent))
    }
}
