//
//  CategoriesListModels.swift
//  ShoppingList
//
//  Created by Mihai on 3/18/17.
//  Copyright (c) 2017 Mihai. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//
//  Type "usecase" for some magic!

import UIKit



struct CategoriesListScene {
    struct GetCategories {
        
        struct Request {
            
        }
        
        struct Response {
            var dataEvent: ListEvent
        }
        
        struct ViewModel {
            var dataEvent: ListEvent
        }
    }
    
    struct MoveCategory {
        
        struct Request {
            var fromIndex: IndexPath
            var toIndex: IndexPath
        }
    }
    
    struct SelectCategory {
        
        struct Request {
            var index: IndexPath
        }
    }
}
