//
//  ShoppingListModels.swift
//  ShoppingList
//
//  Created by Mihai on 3/11/17.
//  Copyright (c) 2017 Mihai. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//
//  Type "usecase" for some magic!

import UIKit



struct ShoppingListScene {
    struct GetItems {
        
        struct Request {
            
        }
        
        struct Response {
            var dataEvent: ListEvent
        }
        
        struct ViewModel {
            var dataEvent: ListEvent
        }
    }
    struct ToggleGrouping {
        
        struct Request {
            
        }
        
        struct Response {
            var grouped: Bool
        }
        
        struct ViewModel {
            var grouped: Bool
        }
    }
    struct ToggleItem {
        
        struct Request {
            var item: ListItem
        }
    }
    struct SelectItem {
        
        struct Request {
            var index: IndexPath?
        }
    }
    struct DeleteItem {
        
        struct Request {
            var item: ListItem
        }
        
        struct Response {
            
        }
        
        struct ViewModel {
            
        }
    }
}
