//
//  ShoppingListConfigurator.swift
//  ShoppingList
//
//  Created by Mihai on 3/11/17.
//  Copyright (c) 2017 Mihai. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

// MARK: Connect View, Interactor, and Presenter

extension ShoppingListInteractor: ShoppingListViewControllerOutput, ShoppingListRouterDataSource, ShoppingListRouterDataDestination {
}

extension ShoppingListPresenter: ShoppingListInteractorOutput {
}

class ShoppingListConfigurator {
    // MARK: Object lifecycle
    
    static let sharedInstance = ShoppingListConfigurator()
    
    private init() {}
    
    // MARK: Configuration
    
    func configure(viewController: ShoppingListViewController) {
        
        let presenter = ShoppingListPresenter()
        presenter.output = viewController
        
        let interactor = ShoppingListInteractor()
        interactor.output = presenter
        interactor.listItemStore = FirebaseListItemStore()
        interactor.itemDataSource = ItemDataSource<ListItem>()
        interactor.categoriesStore = FirebaseCategoryStore()
        
        let router = ShoppingListRouter(viewController:viewController, dataSource:interactor, dataDestination:interactor)
        
        viewController.output = interactor
        viewController.router = router
    }
}
