//
//  ShoppingListPresenter.swift
//  ShoppingList
//
//  Created by Mihai on 3/11/17.
//  Copyright (c) 2017 Mihai. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

protocol ShoppingListPresenterInput {
    func presentDataEvent(response: ShoppingListScene.GetItems.Response)
    func presentGrouping(response: ShoppingListScene.ToggleGrouping.Response)
}

protocol ShoppingListPresenterOutput: class {
    func displayDataEvent(viewmodel: ShoppingListScene.GetItems.ViewModel)
    func displayGrouping(viewmodel: ShoppingListScene.ToggleGrouping.ViewModel)
}

class ShoppingListPresenter: ShoppingListPresenterInput {
    
    weak var output: ShoppingListPresenterOutput!
    
    // MARK: Presentation logic
    func presentDataEvent(response: ShoppingListScene.GetItems.Response) {
       // DispatchQueue.main.async {
            self.output.displayDataEvent(viewmodel: ShoppingListScene.GetItems.ViewModel(dataEvent: response.dataEvent))
       // }
    }
    
    func presentGrouping(response: ShoppingListScene.ToggleGrouping.Response) {
        output.displayGrouping(viewmodel: ShoppingListScene.ToggleGrouping.ViewModel(grouped: response.grouped))
    }
}
